// builtin imports
import { TextEdit, VerticalBox, Button } from "std-widgets.slint";

// custom imports
import { Editor } from "editor/editor.slint";
import { TitleBar } from "titlebar.slint";

// misc
import "monoid/Monoid-Regular-Large.ttf";
import "monoid/Monoid-Bold-Large.ttf";
import "monoid/Monoid-Italic-Large.ttf";
import "monoid/Monoid-Retina-Large.ttf";



// components
export component AppWindow inherits Window
{
    // no-frame: true;
    title: "Sleeplog 0.1.0";
    height: 600px;
    width: 1000px;
    default-font-family: "Monoid";
    default-font-size: 12px;

    // window
    VerticalLayout {
        TitleBar {}
        Editor {}
    }

}